trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/RuiRumos74252.sln'
  unittests: '**/TestProject/TestProject.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '$(solution)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '$(unittests)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true

