trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/RuiRumos74252.sln'
  unittests: '**/TestProject/TestProject.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  azureSubscription: '0c279d29-0c31-44bc-8797-7839cfae9ca8'
  appName: 'RuiRumos74252'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/RuiRumos74252.sln'
    feedsToUse: 'select'
    vstsFeed: '3357f51f-0f3a-40fe-8816-ec45ae9c8862'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '$(solution)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '$(unittests)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    projects: '**/RuiRumos74252/RuiRumos74252.csproj'
    publishWebProjects: true
    zipAfterPublish: false
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'ruirodriguesrumos74252(0c279d29-0c31-44bc-8797-7839cfae9ca8)'
    appType: 'webApp'
    WebAppName: 'RuiRumos74252'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'