
trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/RuiRumos74252.sln'
  unittests: '**/TestProject/TestProject.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

jobs:
  - job: Build
    displayName: 'Build and Test'
    steps:
      - task: NuGetToolInstaller@1

      - task: NuGetCommand@2
        inputs:
          restoreSolution: '$(solution)'

      - task: DotNetCoreCLI@2
        displayName: 'Build'
        inputs:
          command: 'build'
          projects: '$(solution)'

      - task: DotNetCoreCLI@2
        displayName: 'Run Unit Tests'
        inputs:
          command: 'test'
          projects: '$(unittests)'

  - job: Deploy
    displayName: 'Deploy to Azure Web App'
    dependsOn: Build
    condition: succeeded('Build')
    steps:
      - task: AzureWebApp@1
        displayName: 'Azure Web App Deploy'
        inputs:
          azureSubscription: '0c279d29-0c31-44bc-8797-7839cfae9ca8'  
          appName: 'RuiRumos74252'  
          package: '$(System.DefaultWorkingDirectory)/**/*.zip'

